Car department project dropdown unsetting
dodoas/lodo pull request #402
Opened 2017-02-02 12:44 UTC by agvald

Closes #390

2017-02-02 15:09 UTC, mladjo2505 submitted a review, later dismissed
All looks good, but needs extensive testing before we allow it to go on live. 
Also there are some discussions about what is the wanted behaviour for some pages. I leave that for final review.

2017-02-02 15:26 UTC, agvald commented
Before this PR is meged we need to:
 - rebased on master after PR #379 is merged
 - add some small additional changes to journal.edit

2017-02-20 08:36 UTC, mladjo2505 approved these changes
All good with new stuff

2017-02-21 10:29 UTC, stoivo requested changes
Translate

2017-02-21 10:29 UTC, stoivo commented on code/lib/db/db_mysqli.class.php
> +                    #Should we check if it is funsctions here? no.
functions?

2017-02-21 10:29 UTC, stoivo commented on modules/salary/view/template.php
> +            print $_lib['form2']->Car_menu2(array('table'=>$db_table2, 'field'=>'CarID', 'pk'=>$line->SalaryConfLineID, 'value'=>$line->CarID, 'active_reference_date'=>$_lib['sess']->get_session('Log
Check this on @agvald 💻

2017-02-21 10:29 UTC, stoivo commented on modules/bank/view/record.inc
> +        $reskontroaccountplan = $accounting->get_accountplan_object($accountline['ReskontroAccountPlanID']);
Where is this

2017-02-21 10:29 UTC, stoivo commented on modules/bank/view/record.inc
> +            unset($accountline['CarID']);
show me

2017-02-22 07:35 UTC, stoivo approved these changes

2017-02-22 07:35 UTC, merged